//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstAppCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public int NRC { get; set; }
        public string ASIGNATURA { get; set; }
        public int CREDITOS { get; set; }
        public string MODALIDAD { get; set; }
        public int PERIODO { get; set; }
    }
}
